version: 2

registries:
  npm-github:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{ secrets.PACKAGES_TOKEN }}

updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
      time: '14:00'
      timezone: 'Europe/Berlin'
    commit-message:
      prefix: chore
      include: scope
    labels:
      - dependencies
    registries:
      - npm-github
